package crud;
// Generated May 7, 2020 3:01:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.StringJoiner;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

    private Integer cityId;
    private String city;
    private short countryId;
    private Date lastUpdate;

    public City() {
    }

    public City(String city, short countryId, Date lastUpdate) {
        this.city = city;
        this.countryId = countryId;
        this.lastUpdate = lastUpdate;
    }

    public Integer getCityId() {
        return this.cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public short getCountryId() {
        return this.countryId;
    }

    public void setCountryId(short countryId) {
        this.countryId = countryId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        return new StringJoiner(" ").add(city).add(lastUpdate.toString()).toString();

    }
}
//return new StringJoiner(" ").add(firstName).add(lastName).add(lastUpdate.toString()).toString();

